### PR TITLE
Dockerize application using multi-stage builds

### PR DESCRIPTION
**Pull request by LeoVerto**
I've written a Dockerfile to build an image based on `rust-slim`.
I haven't tested this yet as I'm having trouble building the docker image for the webrtc branch of mumble-web right now.

One thing I'm a bit unhappy about is the current image  size of 850MB, a lot of that seems to be due to the `libnice` dependency that pulls in a bunch of other apt packages including - for some reason - python.

I spent some time trying to get [an image continuing only a statically linked binary](https://dev.to/deciduously/use-multi-stage-docker-builds-for-statically-linked-rust-binaries-3jgd) to work but ultimately failed, possibly due to my inexperience with rust.

### CODE REVIEW

**Comment by JuniorJPDJ** [comment]
Oh, just saw this.. I opened #24 yesterday.


> libnice dependency that pulls in a bunch of other apt packages including - for some reason - python.

Try disabling installation of recommended packages in APT or use alpine.

**Comment by haslersn** [comment]
I made a [mumble-web-proxy Docker container](https://git.stuvus.uni-stuttgart.de/ref-it/docker-mumble-web-proxy/-/tree/20dc94b7571ae67a2b0b80de711fd720fad8f765/) of size 25.75 MiB.

**Comment by JuniorJPDJ** [comment]
@haslersn would you like to do pull request with it?
You may also add example docker-compose.

**Comment by haslersn** [comment]
@JuniorJPDJ I can do so. Do you know if there's a more clean way to do this?

```
RUN echo -e '\n[dependencies."async-trait"]\ndefault-features = false' >> Cargo.toml
```

(It's required because I had to use `RUSTFLAGS="-C target-feature=-crt-static"` which in turn I had to use because of a problem with dynamically linking libclang.)

**Comment by JuniorJPDJ** [comment]
Unfortunately no, but I'll leave it, it doesn't seem very bad.

**Comment by ricardojlrufino** [comment]
> I made a [mumble-web-proxy Docker container](https://git.stuvus.uni-stuttgart.de/ref-it/docker-mumble-web-proxy/-/tree/20dc94b7571ae67a2b0b80de711fd720fad8f765/) of size 25.75 MiB.

Please push to docher hub...

**Comment by JuniorJPDJ** [comment]
or add pull request here with it ;)

**Comment by haslersn** [comment]
I didn't add a PR, yet, because I didn't have time to create your requested docker-compose example.

https://hub.docker.com/r/haslersn/mumble-web-proxy

**Comment by ricardojlrufino** [comment]
> I didn't add a PR, yet, because I didn't have time to create your requested docker-compose example.
> 
> https://hub.docker.com/r/haslersn/mumble-web-proxy

@haslersn do you have the docker commands to make the set (3 containers) work? I'm trying but it doesn't work.

**Comment by JuniorJPDJ** [comment]
@haslersn just add Dockerfile, compose can go later or someone else could add it (eg. me if I had time)

**Comment by LeoVerto** [comment]
This PR has been improved on by #29 and thus made redundant.

**Pull request closed without merging**
